# Generated by Django 5.2.6 on 2025-09-16 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('speciality', models.CharField(max_length=200)),
                ('therapy', models.CharField(max_length=100)),
                ('available_days', models.CharField(default='Mon-Fri', max_length=100)),
                ('available_time', models.CharField(default='10:00 AM - 5:00 PM', max_length=100)),
            ],
        ),
    ]
